Support supplying image url with path component
dailymuse/pilbox pull request #1
Opened 2017-08-07 21:23 UTC by sbly

Necessary for [this ticket](https://themuse.atlassian.net/browse/SVC-209)

2017-08-07 21:39 UTC, ian-axelrod commented
Do we want to get tests working for this?

2017-08-07 21:55 UTC, sbly commented
@ian-axelrod I'm working on getting tests set up locally (I get to use Vagrant again!). I don't think it's worthwhile to get a CI setup going

2017-08-07 22:03 UTC, sbly commented
Alright tests pass locally. Only a single test fails, which is due to a timeout error, and it also fails on master so it's just flaky.

2017-08-07 22:11 UTC, ian-axelrod commented
Ok, as long as tests pass in `pilbox-docker` pointing to the new repo, that's fine.

2017-08-07 22:13 UTC, ian-axelrod requested changes

2017-08-07 22:13 UTC, ian-axelrod commented on pilbox/app.py
> +        return [(r"/(.*)", ImageHandler)]
Is this the only functional change? If so, can we not bother making other changes to the fork? I hate it when forks diverge substantially from the original version, as that makes merging upstream more tedious.

2017-08-07 22:31 UTC, sbly commented on pilbox/app.py
> +        return [(r"/(.*)", ImageHandler)]
I don't believe this is going to get merged upstream. Also, I'm not sure exactly what you're asking here?

2017-08-07 22:52 UTC, ian-axelrod commented on pilbox/app.py
> +        return [(r"/(.*)", ImageHandler)]
The other changes you made just appear to be refactors. This particular change is the one that satisfies the ticket requirements, correct?

2017-08-08 02:55 UTC, ysimonson commented
This is a pretty big divergence from pilbox upstream, which means we'll merge the latest updates from upstream even more rarely. Before we go down this route, let's discuss tomorrow and see what other options there might be?

2017-08-08 14:21 UTC, sbly commented on pilbox/app.py
> +        return [(r"/(.*)", ImageHandler)]
This is the only change I made

2017-08-08 14:25 UTC, sbly commented
@ysimonson OK, happy to discuss

2017-08-08 16:57 UTC, ian-axelrod commented on pilbox/app.py
> +        return [(r"/(.*)", ImageHandler)]
?? But I see 'Two files modified' and more than one commit.

2017-08-08 17:03 UTC, sbly commented on pilbox/app.py
> +        return [(r"/(.*)", ImageHandler)]
I'm not sure what you're confused about. I had to make these changes to get the code to work. I couldn't just change this one line. Happy to discuss on slack if you want me to go over the changes

2017-08-09 21:07 UTC, sbly commented
@ysimonson It looks like this is the solution that we're going with. Good to merge?

2017-08-10 16:50 UTC, sbly commented on pilbox/app.py
> +        return [(r"/(.*)", ImageHandler)]
Is this good?

2017-08-10 18:58 UTC, ysimonson approved these changes

2017-08-10 19:21 UTC, ian-axelrod approved these changes

2017-08-10 19:36 UTC, merged